package com1028_coursework;

import java.sql.SQLException;
/** 3.Compute the profit generated by each product line, sorted by profit descending*/
public class SETDRequirement3 {
	public static void main(String[] args) throws SQLException {
		ProfitDescending prof = new ProfitDescending();
		prof.getProductlines();
		prof.DisplayProfitDescending();
		prof.TerminateConnection();

	}
}